service: image-repo-backend-functions

frameworkVersion: "2"

custom:
  bucket: dev-image-repo-bucket

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:custom.bucket}"
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  list:
    handler: list_s3_objects.list
    events:
      - http:
          path: list
          method: get
          cors: true
  uploadImage:
    handler: get_signed_upload.request_upload_URL
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - http:
          path: upload-node
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:788105770206:userpool/us-east-2_PIH6DSP6A
            identitySource: method.request.header.Authorization
            type: token
