---
name: Build
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        working-directory: ./frontend
        run: yarn install

      - name: Lint
        working-directory: ./frontend
        run: yarn lint

      - name: Build
        working-directory: ./frontend
        run: yarn build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./frontend
        run: |
          aws s3 cp \
            --recursive \
            --region us-east-2 \
            dist s3://image-repo-frontend
